apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: bookhub
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://hi:bye@cluster0.xosnjiu.mongodb.net/recruit_dev?retryWrites=true&w=majority